# Generated by Django 4.1.3 on 2023-01-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0002_feedbackdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackdata',
            name='user_name',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
